---
- hosts: service
  tasks:
    - name: Create destination dir
      file:
        path: '{{ aim_base_dir }}'
        state: directory
        mode: 0755
      tags: setup

    - name: Copy run script
      vars:
        binary_dest: '{{ aim_base_dir }}'
      template:
        src: templates/run.sh.j2
        dest: '{{ aim_base_dir }}/run.sh'
        mode: 0755
      tags: setup

    - name: Installing marketing into supervisor
      vars:
        binary_name: AiMarketing
        program_name: '{{ aim_program_name }}'
        binary_dest: '{{ aim_base_dir }}'
      become: true
      template:
        src: templates/supervisor.conf.j2
        dest: '{{ supervisor_conf_dir }}/{{ program_name }}.conf'
      tags: setup

    - name: Build marketing binary
      local_action: command go install github.com/phongle318/AiMarketing
      tags: marketing

    - name: Copy binary
      copy:
        src: "{{ go_path }}/bin/AiMarketing"
        dest: "{{ aim_base_dir }}"
        mode: 0755
      tags: marketing

    - name: Copy order template 
      copy:
        src: "{{ go_path }}/bin/marketing.html"
        dest: "{{ aim_base_dir }}"
        mode: 0755
      tags: [template]

    - name: Restart service
      become: true
      supervisorctl:
        name: AiMarketing
        state: restarted
      tags: [marketing,config]
